CREATE TABLE HABITAT(
   id_habitat INT AUTO_INCREMENT,
   TITLE VARCHAR(100),
   IMG VARCHAR(250),
   IMG2 VARCHAR(250),
   DESCRIPTION TEXT,
   PRIMARY KEY(id_habitat)
);

CREATE TABLE MISSION(
   ID INT AUTO_INCREMENT,
   NAME VARCHAR(50),
   LOGO VARCHAR(150),
   DESCRIPTION TEXT,
   PRIMARY KEY(ID)
);

CREATE TABLE PRESTATION(
   ID INT AUTO_INCREMENT,
   NAME VARCHAR(50),
   LOGO VARCHAR(150),
   DESCRIPTION TEXT,
   PRIMARY KEY(ID)
);

CREATE TABLE ALIMENTATION(
   ID_alimentation INT AUTO_INCREMENT,
   NAME VARCHAR(50),
   DESCRIPTION TEXT,
   QUANTITE VARCHAR(250),
   PRIMARY KEY(ID_alimentation)
);

CREATE TABLE _USER(
   ID_user INT AUTO_INCREMENT,
   NAME VARCHAR(150),
   ROLE VARCHAR(50),
   EMAIL VARCHAR(150),
   PASSWORD VARCHAR(250),
   PRIMARY KEY(ID_user)
);

CREATE TABLE ANIMAUX(
   ID_animaux INT AUTO_INCREMENT,
   IMG VARCHAR(150),
   IMG2 VARCHAR(150),
   TITLE VARCHAR(50),
   DESCRIPTION TEXT,
   SANTE VARCHAR(250),
   SOIN TEXT,
   ID_alimentation INT NOT NULL,
   id_habitat INT NOT NULL,
   PRIMARY KEY(ID_animaux),
   FOREIGN KEY(ID_alimentation) REFERENCES ALIMENTATION(ID_alimentation),
   FOREIGN KEY(id_habitat) REFERENCES HABITAT(id_habitat)
);

CREATE TABLE CARE(
   ID_animaux INT,
   ID_user INT,
   PRIMARY KEY(ID_animaux, ID_user),
   FOREIGN KEY(ID_animaux) REFERENCES ANIMAUX(ID_animaux),
   FOREIGN KEY(ID_user) REFERENCES _USER(ID_user)
);
